### ISSUE TITLE
Dask warning

### ISSUE THREAD

**Issue by bidhya** [ozak/georasters#37]
Upon updating my python installation with conda update --all, I started seeing the following error when importing georasters with command -
`import georasters as grs`

> AppData\Local\Continuum\anaconda3\lib\site-packages\dask\config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
>   data = yaml.load(f.read()) or {}

**Comment by ozak** [comment]
@bidhya I am not sure that is related to ``georasters`` directly. Since this is a ``dask`` message, and georasters does not use ``dask`` (at least directly). Perhaps one of the packages that it uses (see requirements) is importing ``dask``. I do not see this in my setup, so I am not sure which package is causing this. Can you try creating an environment with only ``georasters`` and dependencies? Let me know if you still find the issue. Also, what is the version of these dependencies is?
