### ISSUE TITLE
Trouble with map_pixel

### ISSUE THREAD

**Issue by bekerov** [ozak/georasters#9]
Hello. Thank for lib.
Im trying get pixel value by array index from image below using `col, row = data.map_pixel(0, 0)`.
But i get error `IndexError: index 37643 is out of bounds for axis 0 with size 386`
![img](https://cloud.githubusercontent.com/assets/2405629/20230415/e94d7ba0-a86c-11e6-97c2-4755d571186c.png)

Please help.

**Comment by ozak** [comment]
@bekerov if understand what you want, you should use

    value = data.map_pixel(0, 0)

**Comment by bekerov** [comment]
i think calculating of pixel coordinates is incorrect.
Because image have size by axis 386, but lib trying get 37643.

**Comment by ozak** [comment]
@bekerov Please view my previous comment. You are using the wrong command on the left-hand side.

**Comment by bekerov** [comment]
same error

**Comment by ozak** [comment]
@bekerov  can you provide the data and code so that I can check?

**Comment by bekerov** [comment]
Sure. I added Jupyter notebook with error and image
[error.zip](https://github.com/ozak/georasters/files/628410/error.zip)

**Comment by ozak** [comment]
@bekerov ok I aws able to figure out what was wrong...the problem is that (0,0) is not in the raster. If you look at the geotransform ``data.geot`` you get ``(84.03874732564896, 0.0015088062443882346, 0.0,
 56.79680433777558, 0.0, -0.0015088062443882346)``. So e.g. the first cell in your ``tif`` is at ``(84.03874732564896,56.79680433777558)``

   value = data.map_pixel(84.03874732564896,56.79680433777558)
   print(value)
   print(data.raster[0,0])
   print(vale == data.raster[0,0])

I will try to put an error message to let the user know they have asked for a location outside the coverage of their data. Thanks for pointing this out!

**Comment by bekerov** [comment]
oh thanks, also please specify documentation to function. This will be very helpful
